// Cypress.Command.add('Register', (email,loggingName,password) => {
//     beforeEach(() => {
//         cy.visit('https://www.automationexercise.com')
//     })
//     it.only('passes', () => {
//         let random = Math.round((Math.random()*1000))
//         const loggingName="Temo"+random
//         cy.get('.active > :nth-child(1) > h2').should("be.visible")
//         cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
//         cy.get('.signup-form > h2').should("be.visible")
//         cy.get('[data-qa="signup-name"]').type("Temo"+random)
//         cy.get('[data-qa="signup-email"]').type(email)
//         cy.get('[data-qa="signup-button"]').click()
//         cy.get('#id_gender1').click()
//         cy.get('[data-qa="password"]').type(password)
//         cy.get('[data-qa="days"]').select("3")
//         cy.get('[data-qa="months"]').select("December")
//         cy.get('[data-qa="years"]').select("1987")
//         cy.get('#newsletter').check()
//         cy.get('#optin').check()
//         cy.get('[data-qa="first_name"]').type("Temo")
//         cy.get('[data-qa="last_name"]').type("Galustiani")
//         cy.get('[data-qa="company"]').type("Microsoft")
//         cy.get('[data-qa="address"]').type("Road 66")
//         cy.get('[data-qa="address2"]').type("Lado Asatiani 32")
//         cy.get('[data-qa="country"]').select("United States")
//         cy.get('[data-qa="state"]').type("NY")
//         cy.get('[data-qa="city"]').type("New York")
//         cy.get('[data-qa="zipcode"]').type("07707")
//         cy.get('[data-qa="mobile_number"]').type("593009636")
//         cy.get('[data-qa="create-account"]').click()
//         cy.contains("Account Created!").should("be.visible")
//         cy.get('[data-qa="continue-button"]').click()
//         cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
//     })
// })