describe('template spec', () => {
    it('passes', () => {
      cy.visit('https://automationteststore.com/')
cy.get('#customer_menu_top > li > a').click()
cy.get('.newcustomer > .heading2').should("be.visible")
cy.get('.newcustomer > .heading2').should("contain","I am a new")
cy.get('#accountFrm_accountregister').should("be.checked")
cy.get('#accountFrm > fieldset > .btn').click()
cy.get('#AccountFrm_firstname').type("Temo")
cy.get('#AccountFrm_lastname').type("Galustiani")
cy.get('#AccountFrm_email').type("temo-galustian@gmail.com")
cy.get('#AccountFrm_address_1').type("Tbilisi")
cy.get('#AccountFrm_city').type("Tbilisi")
cy.get('#AccountFrm_zone_id').select("Aberdeen")
cy.get('#AccountFrm_postcode').type("0108")
cy.get('#AccountFrm_country_id').select("Tunisia")
cy.get('#AccountFrm_loginname').type("Temo123")
cy.get('#AccountFrm_password').type("12345678")
cy.get('#AccountFrm_confirm').type("12345678")
cy.get('#AccountFrm_newsletter1').check()
cy.get('#AccountFrm_agree').check()
cy.get('.col-md-2 > .btn').click()
    })
})